/**
 * AI Subconscious - Persistent Memory System for AI Personalities
 *
 * Inspired by Letta's memory architecture, this provides each AI with:
 * - Structured memory blocks (persona, human, relationships, patterns)
 * - Async transcript processing for pattern detection
 * - Self-improving behavior over time
 * - Cross-session learning and continuity
 *
 * Works with any LLM backend (Ollama, local models, etc.)
 */

package com.landseek.aichat.domain.model

import kotlinx.coroutines.*
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.File
import java.time.Instant
import java.util.concurrent.ConcurrentHashMap

// ========== Memory Block Types ==========

/**
 * Types of memory blocks in the subconscious.
 */
enum class MemoryBlockType(val value: String) {
    PERSONA("persona"),           // AI's core identity, traits, directives
    HUMAN("human"),               // What AI learned about the primary user
    RELATIONSHIPS("relationships"), // Knowledge about other participants/AIs
    PATTERNS("patterns"),         // Learned interaction patterns
    PENDING("pending"),           // Items to follow up on
    INSIGHTS("insights"),         // Cross-session observations
    PREFERENCES("preferences"),   // User preferences detected over time
    SKILLS("skills")              // Capabilities the AI has learned/improved
}

/**
 * A single memory block with content and metadata.
 */
@Serializable
data class MemoryBlock(
    val type: String,
    var content: String,
    var lastUpdated: String = Instant.now().toString(),
    var updateCount: Int = 0,
    val metadata: MutableMap<String, String> = mutableMapOf()
) {
    fun update(newContent: String) {
        content = newContent
        lastUpdated = Instant.now().toString()
        updateCount++
    }

    fun append(addition: String) {
        content = if (content.isBlank()) addition else "$content\n$addition"
        lastUpdated = Instant.now().toString()
        updateCount++
    }
}

/**
 * A detected pattern from conversation analysis.
 */
@Serializable
data class DetectedPattern(
    val patternId: String,
    val category: String,        // "coding_style", "topic_preference", "communication", etc.
    val description: String,
    val confidence: Float,       // 0.0 to 1.0
    val occurrences: Int,
    val firstSeen: String,
    val lastSeen: String,
    val examples: List<String> = emptyList()
)

/**
 * A conversation transcript entry for analysis.
 */
@Serializable
data class TranscriptEntry(
    val role: String,            // "user", "assistant", "system"
    val content: String,
    val timestamp: String,
    val participantId: String? = null,
    val participantName: String? = null
)

/**
 * Session summary generated by the subconscious.
 */
@Serializable
data class SessionSummary(
    val sessionId: String,
    val startTime: String,
    val endTime: String,
    val messageCount: Int,
    val topicsDiscussed: List<String>,
    val newInsights: List<String>,
    val pendingItems: List<String>,
    val moodProgression: List<String> = emptyList()
)

/**
 * Subconscious state for persistence.
 */
@Serializable
data class SubconsciousState(
    val aiId: String,
    val memoryBlocks: Map<String, MemoryBlock>,
    val patterns: List<DetectedPattern>,
    val sessionHistory: List<SessionSummary>,
    val lastProcessedSession: String? = null,
    val totalInteractions: Int = 0,
    val createdAt: String = Instant.now().toString()
)

// ========== AI Subconscious Implementation ==========

/**
 * AI Subconscious - The "background mind" of an AI personality.
 *
 * This class manages persistent memory that evolves over time through:
 * - Conversation transcript analysis
 * - Pattern detection and learning
 * - Self-updating memory blocks
 * - Cross-session continuity
 */
class AISubconscious(
    private val aiId: String,
    private val aiName: String,
    private val storageDir: String,
    private val ragStore: AIRAGStore? = null
) {
    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())
    private val json = Json { prettyPrint = true; ignoreUnknownKeys = true }

    // Memory blocks
    private val memoryBlocks = ConcurrentHashMap<String, MemoryBlock>()

    // Detected patterns
    private val patterns = ConcurrentHashMap<String, DetectedPattern>()

    // Session history
    private val sessionHistory = mutableListOf<SessionSummary>()

    // Current session transcript
    private val currentTranscript = mutableListOf<TranscriptEntry>()
    private var currentSessionId: String = generateSessionId()
    private var sessionStartTime: String = Instant.now().toString()

    // Stats
    private var totalInteractions = 0

    init {
        initializeMemoryBlocks()
        loadFromDisk()
    }

    // ========== Public API ==========

    /**
     * Record a message in the current transcript.
     */
    fun recordMessage(
        role: String,
        content: String,
        participantId: String? = null,
        participantName: String? = null
    ) {
        currentTranscript.add(
            TranscriptEntry(
                role = role,
                content = content,
                timestamp = Instant.now().toString(),
                participantId = participantId,
                participantName = participantName
            )
        )
        totalInteractions++

        // Trigger async analysis periodically
        if (currentTranscript.size % 10 == 0) {
            scope.launch { analyzeRecentMessages() }
        }
    }

    /**
     * End the current session and process the transcript.
     */
    fun endSession() {
        scope.launch {
            processSessionTranscript()
            currentTranscript.clear()
            currentSessionId = generateSessionId()
            sessionStartTime = Instant.now().toString()
            saveToDisk()
        }
    }

    /**
     * Get a memory block by type.
     */
    fun getMemoryBlock(type: MemoryBlockType): MemoryBlock? {
        return memoryBlocks[type.value]
    }

    /**
     * Get all memory blocks.
     */
    fun getAllMemoryBlocks(): Map<String, MemoryBlock> {
        return memoryBlocks.toMap()
    }

    /**
     * Update a memory block directly.
     */
    fun updateMemoryBlock(type: MemoryBlockType, content: String) {
        memoryBlocks[type.value]?.update(content)
        saveToDiskAsync()
    }

    /**
     * Append to a memory block.
     */
    fun appendToMemoryBlock(type: MemoryBlockType, content: String) {
        memoryBlocks[type.value]?.append(content)
        saveToDiskAsync()
    }

    /**
     * Get detected patterns.
     */
    fun getPatterns(): List<DetectedPattern> {
        return patterns.values.toList()
    }

    /**
     * Get patterns by category.
     */
    fun getPatternsByCategory(category: String): List<DetectedPattern> {
        return patterns.values.filter { it.category == category }
    }

    /**
     * Get session history.
     */
    fun getSessionHistory(): List<SessionSummary> {
        return sessionHistory.toList()
    }

    /**
     * Build context string for LLM prompts.
     * This is what gets injected into the AI's system prompt.
     */
    fun buildContextForPrompt(): String {
        val sb = StringBuilder()

        // Core persona (always included)
        memoryBlocks[MemoryBlockType.PERSONA.value]?.let {
            sb.appendLine("## Your Identity")
            sb.appendLine(it.content)
            sb.appendLine()
        }

        // What you know about the user
        memoryBlocks[MemoryBlockType.HUMAN.value]?.let {
            if (it.content.isNotBlank()) {
                sb.appendLine("## About the User")
                sb.appendLine(it.content)
                sb.appendLine()
            }
        }

        // User preferences
        memoryBlocks[MemoryBlockType.PREFERENCES.value]?.let {
            if (it.content.isNotBlank()) {
                sb.appendLine("## User Preferences")
                sb.appendLine(it.content)
                sb.appendLine()
            }
        }

        // Pending items to remember
        memoryBlocks[MemoryBlockType.PENDING.value]?.let {
            if (it.content.isNotBlank()) {
                sb.appendLine("## Things to Remember")
                sb.appendLine(it.content)
                sb.appendLine()
            }
        }

        // Recent insights
        memoryBlocks[MemoryBlockType.INSIGHTS.value]?.let {
            if (it.content.isNotBlank()) {
                sb.appendLine("## Recent Insights")
                sb.appendLine(it.content)
                sb.appendLine()
            }
        }

        // High-confidence patterns
        val topPatterns = patterns.values
            .filter { it.confidence >= 0.7f }
            .sortedByDescending { it.confidence }
            .take(5)

        if (topPatterns.isNotEmpty()) {
            sb.appendLine("## Learned Patterns")
            topPatterns.forEach { pattern ->
                sb.appendLine("- ${pattern.description}")
            }
            sb.appendLine()
        }

        return sb.toString().trim()
    }

    /**
     * Get a summary of the subconscious state.
     */
    fun getSummary(): Map<String, Any> {
        return mapOf(
            "aiId" to aiId,
            "aiName" to aiName,
            "totalInteractions" to totalInteractions,
            "memoryBlockCount" to memoryBlocks.size,
            "patternCount" to patterns.size,
            "sessionCount" to sessionHistory.size,
            "currentSessionMessages" to currentTranscript.size
        )
    }

    /**
     * Learn about a specific participant.
     */
    fun learnAboutParticipant(participantId: String, participantName: String, observation: String) {
        val relationshipsBlock = memoryBlocks[MemoryBlockType.RELATIONSHIPS.value]
        val current = relationshipsBlock?.content ?: ""

        // Check if we already have info about this participant
        val existingInfo = current.lines().find { it.startsWith("$participantName:") }

        val updated = if (existingInfo != null) {
            // Update existing
            current.replace(existingInfo, "$participantName: $observation")
        } else {
            // Add new
            if (current.isBlank()) "$participantName: $observation"
            else "$current\n$participantName: $observation"
        }

        relationshipsBlock?.update(updated)
        saveToDiskAsync()
    }

    /**
     * Add a pending item to follow up on.
     */
    fun addPendingItem(item: String) {
        appendToMemoryBlock(MemoryBlockType.PENDING, "- $item")
    }

    /**
     * Clear a pending item (mark as resolved).
     */
    fun resolvePendingItem(item: String) {
        val pendingBlock = memoryBlocks[MemoryBlockType.PENDING.value]
        pendingBlock?.let {
            val lines = it.content.lines().filter { line ->
                !line.contains(item, ignoreCase = true)
            }
            it.update(lines.joinToString("\n"))
        }
        saveToDiskAsync()
    }

    /**
     * Force save to disk.
     */
    fun save() {
        saveToDisk()
    }

    // ========== Private Methods ==========

    private fun initializeMemoryBlocks() {
        // Initialize all memory block types with defaults
        MemoryBlockType.entries.forEach { type ->
            val defaultContent = when (type) {
                MemoryBlockType.PERSONA -> "I am $aiName, an AI assistant."
                MemoryBlockType.HUMAN -> ""
                MemoryBlockType.RELATIONSHIPS -> ""
                MemoryBlockType.PATTERNS -> ""
                MemoryBlockType.PENDING -> ""
                MemoryBlockType.INSIGHTS -> ""
                MemoryBlockType.PREFERENCES -> ""
                MemoryBlockType.SKILLS -> ""
            }
            memoryBlocks[type.value] = MemoryBlock(
                type = type.value,
                content = defaultContent
            )
        }
    }

    private fun generateSessionId(): String {
        return "session_${Instant.now().toEpochMilli()}_${(1000..9999).random()}"
    }

    private suspend fun analyzeRecentMessages() = withContext(Dispatchers.Default) {
        if (currentTranscript.size < 5) return@withContext

        val recentMessages = currentTranscript.takeLast(10)

        // Detect communication patterns
        detectCommunicationPatterns(recentMessages)

        // Detect topic patterns
        detectTopicPatterns(recentMessages)

        // Update user knowledge
        updateUserKnowledge(recentMessages)
    }

    private fun detectCommunicationPatterns(messages: List<TranscriptEntry>) {
        val userMessages = messages.filter { it.role == "user" }

        // Detect question frequency
        val questionCount = userMessages.count { it.content.contains("?") }
        if (questionCount > userMessages.size * 0.7) {
            addOrUpdatePattern(
                category = "communication",
                description = "User frequently asks questions - prefer informative responses",
                confidence = 0.6f + (questionCount.toFloat() / userMessages.size) * 0.3f
            )
        }

        // Detect code-heavy conversations
        val codeBlockCount = messages.count {
            it.content.contains("```") || it.content.contains("def ") ||
                it.content.contains("fun ") || it.content.contains("class ")
        }
        if (codeBlockCount > messages.size * 0.3) {
            addOrUpdatePattern(
                category = "topic_preference",
                description = "User frequently discusses code - provide code examples when relevant",
                confidence = 0.5f + (codeBlockCount.toFloat() / messages.size) * 0.4f
            )
        }

        // Detect brevity preference
        val avgUserMessageLength = userMessages.map { it.content.length }.average()
        if (avgUserMessageLength < 100) {
            addOrUpdatePattern(
                category = "communication",
                description = "User prefers brief messages - keep responses concise",
                confidence = 0.7f
            )
        } else if (avgUserMessageLength > 300) {
            addOrUpdatePattern(
                category = "communication",
                description = "User provides detailed context - thorough responses appreciated",
                confidence = 0.7f
            )
        }
    }

    private fun detectTopicPatterns(messages: List<TranscriptEntry>) {
        val allContent = messages.joinToString(" ") { it.content.lowercase() }

        // Topic keywords to detect
        val topicKeywords = mapOf(
            "programming" to listOf("code", "function", "class", "variable", "debug", "error", "compile"),
            "android" to listOf("android", "kotlin", "activity", "fragment", "compose", "gradle"),
            "ai_ml" to listOf("model", "training", "neural", "llm", "embedding", "vector"),
            "web" to listOf("html", "css", "javascript", "react", "api", "http"),
            "data" to listOf("database", "sql", "query", "table", "json", "csv")
        )

        for ((topic, keywords) in topicKeywords) {
            val matchCount = keywords.count { allContent.contains(it) }
            if (matchCount >= 3) {
                addOrUpdatePattern(
                    category = "topic_preference",
                    description = "User shows interest in $topic topics",
                    confidence = minOf(0.5f + matchCount * 0.1f, 0.95f)
                )
            }
        }
    }

    private fun updateUserKnowledge(messages: List<TranscriptEntry>) {
        val userMessages = messages.filter { it.role == "user" }

        // Look for self-identifying statements
        for (msg in userMessages) {
            val content = msg.content

            // "I am a..." or "I'm a..."
            val professionMatch = Regex("(?i)i('m| am) a[n]? ([\\w\\s]+)(?:developer|engineer|designer|student|researcher)")
                .find(content)
            if (professionMatch != null) {
                val profession = professionMatch.groupValues[2].trim()
                updateHumanKnowledge("profession", profession)
            }

            // "I work on..." or "I'm working on..."
            val projectMatch = Regex("(?i)i('m| am)? work(?:ing)? on ([\\w\\s]+)")
                .find(content)
            if (projectMatch != null) {
                val project = projectMatch.groupValues[2].trim().take(50)
                updateHumanKnowledge("current_project", project)
            }

            // "I prefer..." or "I like..."
            val preferenceMatch = Regex("(?i)i (prefer|like|want) ([\\w\\s]+)")
                .find(content)
            if (preferenceMatch != null) {
                val preference = preferenceMatch.groupValues[2].trim().take(50)
                appendToMemoryBlock(MemoryBlockType.PREFERENCES, "- $preference")
            }
        }
    }

    private fun updateHumanKnowledge(key: String, value: String) {
        val humanBlock = memoryBlocks[MemoryBlockType.HUMAN.value] ?: return
        val currentLines = humanBlock.content.lines().toMutableList()

        // Find and update existing key or add new
        val existingIndex = currentLines.indexOfFirst { it.startsWith("$key:") }
        if (existingIndex >= 0) {
            currentLines[existingIndex] = "$key: $value"
        } else {
            currentLines.add("$key: $value")
        }

        humanBlock.update(currentLines.filter { it.isNotBlank() }.joinToString("\n"))
    }

    private fun addOrUpdatePattern(
        category: String,
        description: String,
        confidence: Float,
        examples: List<String> = emptyList()
    ) {
        val patternId = "${category}_${description.hashCode().toString(16)}"
        val existing = patterns[patternId]

        if (existing != null) {
            // Update existing pattern
            patterns[patternId] = existing.copy(
                confidence = minOf((existing.confidence + confidence) / 2 + 0.05f, 1.0f),
                occurrences = existing.occurrences + 1,
                lastSeen = Instant.now().toString(),
                examples = (existing.examples + examples).takeLast(5)
            )
        } else {
            // Add new pattern
            patterns[patternId] = DetectedPattern(
                patternId = patternId,
                category = category,
                description = description,
                confidence = confidence,
                occurrences = 1,
                firstSeen = Instant.now().toString(),
                lastSeen = Instant.now().toString(),
                examples = examples
            )
        }
    }

    private suspend fun processSessionTranscript() = withContext(Dispatchers.Default) {
        if (currentTranscript.isEmpty()) return@withContext

        // Generate session summary
        val topics = extractTopics(currentTranscript)
        val insights = generateInsights(currentTranscript)
        val pendingItems = extractPendingItems(currentTranscript)

        val summary = SessionSummary(
            sessionId = currentSessionId,
            startTime = sessionStartTime,
            endTime = Instant.now().toString(),
            messageCount = currentTranscript.size,
            topicsDiscussed = topics,
            newInsights = insights,
            pendingItems = pendingItems
        )

        sessionHistory.add(summary)

        // Keep only last 50 sessions
        while (sessionHistory.size > 50) {
            sessionHistory.removeAt(0)
        }

        // Update insights memory block
        if (insights.isNotEmpty()) {
            val insightsBlock = memoryBlocks[MemoryBlockType.INSIGHTS.value]
            val newInsightsText = insights.joinToString("\n") { "- $it" }
            insightsBlock?.let {
                // Keep recent insights, limit to ~20 lines
                val existingLines = it.content.lines().takeLast(15)
                it.update((existingLines + insights.map { i -> "- $i" }).joinToString("\n"))
            }
        }

        // Update pending items
        if (pendingItems.isNotEmpty()) {
            pendingItems.forEach { item ->
                addPendingItem(item)
            }
        }

        // Store in RAG for semantic retrieval
        ragStore?.let { store ->
            val transcriptText = currentTranscript.joinToString("\n") {
                "${it.role}: ${it.content}"
            }
            store.addDocument(
                content = transcriptText,
                source = "session:$currentSessionId",
                sourceType = "conversation",
                metadata = mapOf(
                    "session_id" to currentSessionId,
                    "message_count" to currentTranscript.size.toString()
                )
            )
        }
    }

    private fun extractTopics(transcript: List<TranscriptEntry>): List<String> {
        val allContent = transcript.joinToString(" ") { it.content.lowercase() }
        val topics = mutableListOf<String>()

        val topicPatterns = mapOf(
            "coding" to listOf("code", "function", "bug", "error"),
            "design" to listOf("design", "ui", "ux", "layout"),
            "data" to listOf("data", "database", "query"),
            "ai" to listOf("ai", "model", "llm", "training"),
            "general" to listOf("help", "question", "how to")
        )

        for ((topic, keywords) in topicPatterns) {
            if (keywords.any { allContent.contains(it) }) {
                topics.add(topic)
            }
        }

        return topics.ifEmpty { listOf("general") }
    }

    private fun generateInsights(transcript: List<TranscriptEntry>): List<String> {
        val insights = mutableListOf<String>()

        // Analyze user satisfaction (simple heuristic)
        val userMessages = transcript.filter { it.role == "user" }
        val positiveIndicators = listOf("thanks", "great", "perfect", "awesome", "helpful")
        val negativeIndicators = listOf("wrong", "incorrect", "doesn't work", "still not")

        val positiveCount = userMessages.count { msg ->
            positiveIndicators.any { msg.content.lowercase().contains(it) }
        }
        val negativeCount = userMessages.count { msg ->
            negativeIndicators.any { msg.content.lowercase().contains(it) }
        }

        if (positiveCount > negativeCount && positiveCount > 0) {
            insights.add("Session was generally positive - approach was effective")
        } else if (negativeCount > positiveCount && negativeCount > 0) {
            insights.add("Session had some difficulties - may need to adjust approach")
        }

        // Detect if user asked for clarification
        val clarificationCount = userMessages.count { msg ->
            msg.content.lowercase().let {
                it.contains("what do you mean") || it.contains("can you explain") ||
                    it.contains("i don't understand") || it.contains("clarify")
            }
        }
        if (clarificationCount > 1) {
            insights.add("User needed clarification multiple times - be more explicit")
        }

        return insights
    }

    private fun extractPendingItems(transcript: List<TranscriptEntry>): List<String> {
        val pendingItems = mutableListOf<String>()

        // Look for "later", "tomorrow", "next time", "remind me"
        val pendingPatterns = listOf(
            Regex("(?i)remind me to ([\\w\\s]+)"),
            Regex("(?i)don't forget to ([\\w\\s]+)"),
            Regex("(?i)we should ([\\w\\s]+) later"),
            Regex("(?i)next time,? ([\\w\\s]+)")
        )

        for (entry in transcript) {
            for (pattern in pendingPatterns) {
                pattern.find(entry.content)?.let { match ->
                    val item = match.groupValues.getOrNull(1)?.trim()?.take(100)
                    if (!item.isNullOrBlank()) {
                        pendingItems.add(item)
                    }
                }
            }
        }

        return pendingItems.distinct()
    }

    private fun saveToDiskAsync() {
        scope.launch { saveToDisk() }
    }

    private fun saveToDisk() {
        try {
            val dir = File(storageDir)
            if (!dir.exists()) dir.mkdirs()

            val state = SubconsciousState(
                aiId = aiId,
                memoryBlocks = memoryBlocks.toMap(),
                patterns = patterns.values.toList(),
                sessionHistory = sessionHistory.toList(),
                lastProcessedSession = if (sessionHistory.isNotEmpty())
                    sessionHistory.last().sessionId else null,
                totalInteractions = totalInteractions
            )

            val file = File(dir, "subconscious_$aiId.json")
            file.writeText(json.encodeToString(state))
        } catch (e: Exception) {
            // Log error but don't crash
        }
    }

    private fun loadFromDisk() {
        try {
            val file = File(storageDir, "subconscious_$aiId.json")
            if (!file.exists()) return

            val content = file.readText()
            if (content.isBlank()) return

            val state = json.decodeFromString<SubconsciousState>(content)

            // Restore memory blocks
            state.memoryBlocks.forEach { (key, block) ->
                memoryBlocks[key] = block
            }

            // Restore patterns
            state.patterns.forEach { pattern ->
                patterns[pattern.patternId] = pattern
            }

            // Restore session history
            sessionHistory.clear()
            sessionHistory.addAll(state.sessionHistory)

            totalInteractions = state.totalInteractions
        } catch (e: Exception) {
            // Log error but don't crash - start fresh
        }
    }

    /**
     * Cleanup when done.
     */
    fun shutdown() {
        endSession()
        scope.cancel()
    }
}

// ========== Subconscious Manager ==========

/**
 * Manages subconscious instances for all AI personalities.
 */
class SubconsciousManager(
    private val storageDir: String,
    private val ragManager: RAGManager? = null
) {
    private val instances = ConcurrentHashMap<String, AISubconscious>()

    /**
     * Get or create a subconscious for an AI.
     */
    fun getSubconscious(aiId: String, aiName: String): AISubconscious {
        return instances.getOrPut(aiId) {
            AISubconscious(
                aiId = aiId,
                aiName = aiName,
                storageDir = storageDir,
                ragStore = ragManager?.getStore(aiId)
            )
        }
    }

    /**
     * Check if an AI has a subconscious instance.
     */
    fun hasSubconscious(aiId: String): Boolean {
        return instances.containsKey(aiId)
    }

    /**
     * Remove a subconscious instance.
     */
    fun removeSubconscious(aiId: String) {
        instances.remove(aiId)?.shutdown()
    }

    /**
     * Get all AI IDs with subconscious instances.
     */
    fun getAllAiIds(): Set<String> = instances.keys.toSet()

    /**
     * End all sessions (e.g., on app close).
     */
    fun endAllSessions() {
        instances.values.forEach { it.endSession() }
    }

    /**
     * Shutdown all instances.
     */
    fun shutdown() {
        instances.values.forEach { it.shutdown() }
        instances.clear()
    }
}

// ========== Global Instance ==========

private var subconsciousManagerInstance: SubconsciousManager? = null

fun getSubconsciousManager(storageDir: String = "", ragManager: RAGManager? = null): SubconsciousManager {
    if (subconsciousManagerInstance == null) {
        subconsciousManagerInstance = SubconsciousManager(storageDir, ragManager)
    }
    return subconsciousManagerInstance!!
}
